### ISSUE TITLE
[New Feature] Edit button on Patient Registration page

### ISSUE THREAD

**Issue by sreelakshmiharidos** [kimxw/battambang-clinic-system-2024#60]
On the receptionist's interface(patient registration page), add an edit button alongside add, delete and search buttons to edit a row that has already been entered.

**Comment by kimxw** [comment]
This issue has been addressed in PR https://github.com/kimxw/battambang-clinic-system/pull/26 and the changes have been merged. Closes https://github.com/kimxw/battambang-clinic-system/pull/26
